# Generated by Django 3.2.25 on 2024-12-27 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.customuser')),
                ('position', models.CharField(blank=True, max_length=500, null=True)),
                ('departmental_email', models.CharField(blank=True, max_length=90, null=True)),
            ],
        ),
    ]
