# Generated by Django 3.2.25 on 2024-12-28 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20241228_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalcredentials',
            name='applicant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='additionalcredentials', to='app.application'),
        ),
        migrations.AddField(
            model_name='additionalqualification',
            name='applicant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='additionalqualification', to='app.application'),
        ),
        migrations.AddField(
            model_name='alevelqualification',
            name='applicant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='alevelqualification', to='app.application'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='applicant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='declaration', to='app.application'),
        ),
        migrations.AddField(
            model_name='healthdetail',
            name='applicant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='health_detail', to='app.application'),
        ),
        migrations.AddField(
            model_name='healthdetail',
            name='session',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.session'),
        ),
        migrations.AddField(
            model_name='modeofentry',
            name='applicant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='modeOfEntry', to='app.application'),
        ),
        migrations.AddField(
            model_name='olevelqualification',
            name='applicant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='olevelqualification', to='app.application'),
        ),
        migrations.AddField(
            model_name='parentsguardian',
            name='applicant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='parents_guardian', to='app.application'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='applicant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to='app.application'),
        ),
        migrations.AddField(
            model_name='uploadedcredentials',
            name='applicant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='uploadedcredentials', to='app.application'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='applicant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to='app.application'),
        ),
    ]
